### ISSUE TITLE
Add a PPT explaining the project

### ISSUE THREAD

**Issue by suyashgautam** [suyashgautam/e-Waste-Management#1]

**Comment by OmThakkar** [comment]
I would love to contribute on this issue, but please would you kindly elaborate more about the PPT and the idea part.

**Comment by nishantshukla2884** [comment]
hi Suyash , 
i think i can contribute to this  project 
kindly assign it to me

**Comment by suyashgautam** [comment]
Hey @OmThakkar , Can you please take up #4 ? This has a higher priority.
Regarding this issue i will add more details later on.

**Comment by OmThakkar** [comment]
I think I would be able to do the PPT and documentation part more appropriately as I am not much familiar with React and I have received many recommendations on my PPT design skills so #1 would be the best option.

**Comment by suyashgautam** [comment]
@OmThakkar Can you please take up the task of proofreading the PPT and check if you could improve it for better understanding?
If yes I will create an issue for that and will assign it to you
