### ISSUE TITLE
Create user flow for the project

### ISSUE THREAD

**Issue by suyashgautam** [suyashgautam/e-Waste-Management#2]
Add a user flow in the root of the project explaining the flow.

**Comment by nishantshukla2884** [comment]
hi , i am interested 
kindly assign this to me @suyashgautam

**Comment by suyashgautam** [comment]
Sure, assigned the issue @nishantshukla2884 . Let me know if you face any trouble.

**Comment by nishantshukla2884** [comment]
sure

**Comment by suyashgautam** [comment]
Approved and merged the pull request
